- name: Use ansible 1.9
  sudo: yes
  apt_repository: repo=ppa:ansible/ansible-1.9 state=present

- name: Install packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items: 
    - build-essential
    - git
    - libevent-dev
    - nginx
    - git-core     
    - python-dev
    - python-software-properties
    - python-setuptools
    - python-virtualenv   
    - ansible

- name: Create Base Directory
  sudo: yes
  file: state=directory path={{base_directory}} owner={{deploy_user}} group={{deploy_user}}

- name: Create Env Directory
  sudo: yes
  file: state=directory path={{virtualenv_path}} owner={{deploy_user}} group={{deploy_user}}

- name: Upload SSH key.
  copy: src=~/.ssh/id_rsa 
        dest=/home/{{ deploy_user }}/.ssh/id_rsa mode=0600

- name: Upload SSH key.
  copy: src=~/.ssh/id_rsa.pub 
        dest=/home/{{ deploy_user }}/.ssh/id_rsa.pub mode=0600

- name: Add github to known_hosts
  copy: src=~/.ssh/known_hosts
        dest=/home/{{deploy_user}}/.ssh/

- name: Upload Vault password.
  copy: src=~/.vault_pass.txt
        dest=/home/{{ deploy_user }}/





